export enum EPermissions {
  GET_ARTICLES = 'GET_ARTICLES',
  DELETE_ARTICLES = 'DELETE_ARTICLES',
  PUT_ARTICLES = 'PUT_ARTICLES',
  PATCH_ARTICLES = 'PATCH_ARTICLES',
  GET_USERS = 'GET_USERS',
  DELETE_USERS = 'DELETE_USERS',
  GET_ANY_ARTICLES = 'GET_ANY_ARTICLES',
  DELETE_ANY_ARTICLES = 'DELETE_ANY_ARTICLES',
}
